version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "9475:9475"
    volumes:
      # Mount the source code for hot reloading
      - ./web:/app
      # Exclude node_modules from the mount
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Add any other environment variables your app needs
    command: npm run dev
