version: '3.8'

services:
  couchdb:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        - AUTH_SECRET=${AUTH_SECRET}
        - AUTH_HMAC_KID=${AUTH_HMAC_KID}
    ports:
      - "${COUCHDB_PORT}:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
