version: '3.8'

name: papaya-dev

services:
  couchdb:
    build:
      context: ..
      dockerfile: dev/database/Dockerfile.dev
    ports:
      - "${PAPAYA_COUCHDB_PORT:-5984}:5984"
    environment:
      - COUCHDB_USER=${PAPAYA_COUCHDB_ADMIN_USER:-admin}
      - COUCHDB_PASSWORD=${PAPAYA_COUCHDB_ADMIN_PASS:-password}
      # Environment variables for config substitution
      - PAPAYA_COUCHDB_ADMIN_USER=${PAPAYA_COUCHDB_ADMIN_USER}
      - PAPAYA_COUCHDB_ADMIN_PASS=${PAPAYA_COUCHDB_ADMIN_PASS}
      - AUTH_ACCESS_TOKEN_SECRET=${PAPAYA_TOKEN_SECRET}
    env_file:
      - ../.env
    volumes:
      - couchdb_data:/opt/couchdb/data

  server:
    build:
      context: ..
      dockerfile: dev/server/Dockerfile.dev
    ports:
      - "${PAPAYA_SERVER_PORT:-9475}:${PAPAYA_SERVER_PORT:-9475}"
    environment:
      - NODE_ENV=development
      - PAPAYA_COUCHDB_HOST=http://couchdb
      - PAPAYA_COUCHDB_PORT=${PAPAYA_COUCHDB_PORT:-5984}
    env_file:
      - ../.env
    depends_on:
      - couchdb
    volumes:
      - ../packages/papaya-server:/app
      - server_node_modules:/app/node_modules
    command: npm run dev

  web:
    build:
      context: ..
      dockerfile: dev/client/Dockerfile.dev
    ports:
      - "${PAPAYA_WEB_PORT:-9476}:${PAPAYA_WEB_PORT:-9476}"
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env
    volumes:
      - ../packages/papaya-web:/app
      - web_node_modules:/app/node_modules
    command: npm run dev

volumes:
  couchdb_data:
  server_node_modules:
  web_node_modules: 