services:
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    container_name: couchdb
    env_file:
      - .env
    environment:
      - COUCHDB_USER=${ZISK_COUCHDB_ADMIN_USER}
      - COUCHDB_PASSWORD=${ZISK_COUCHDB_ADMIN_PASS}
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - 5984:5984
    command: ["/bin/bash", "-c", "/usr/local/bin/database-setup.sh && exec /opt/couchdb/bin/couchdb"]

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: node
    env_file:
      - .env
    environment:
      - SERVER_NAME=${ZISK_SERVER_NAME}
      - PORT=9000

  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    container_name: nginx
    ports:
      - "0.0.0.0:${ZISK_SERVER_PORT}:80" # Bind to all interfaces
    depends_on:
      - database
      - api

volumes:
  couchdb_data:
