services:
  database:
    build:
      context: .
      dockerfile: database/database.Dockerfile
    container_name: couchdb
    env_file:
      - .env
    environment:
      - COUCHDB_USER=${ZISK_COUCHDB_ADMIN_USER}
      - COUCHDB_PASSWORD=${ZISK_COUCHDB_ADMIN_PASS}
    volumes:
      - couchdb_data:/opt/couchdb/data

  api:
    build:
      context: .
      dockerfile: api/api.Dockerfile
    container_name: node
    environment:
      - PORT=9000
    volumes:
      - ./api:/usr/src/app

  proxy:
    build:
      context: .
      dockerfile: proxy/proxy.Dockerfile
    container_name: nginx
    ports:
      - "0.0.0.0:${ZISK_SERVER_PORT}:80" # Bind to all interfaces
    depends_on:
      - database
      - api

volumes:
  couchdb_data:
